theme: jekyll-theme-minimal
title: Pierre Pora
description: Economist at <a href="https://insee.fr">Insee</a>, <a href="http://crest.science/">Crest</a> and <a href="https://demographie-economique.site.ined.fr/">Ined</a> affiliate</a>
contact: "pierre.pora[at]ensae.fr"
show_downloads: false
